/**Personal Data Access Control System
 * MainClass
 *
 * Author: Cristòfol Daudén Esmel
 */

import org.web3j.protocol.Web3j;
import org.web3j.protocol.http.HttpService;
import org.web3j.tx.ClientTransactionManager;
import org.web3j.tx.gas.DefaultGasProvider;
import src.main.java.contracts.CollectionConsent;
import src.main.java.contracts.ProcessingConsent;

import java.math.BigInteger;
import java.util.*;
import java.util.concurrent.ExecutionException;
import java.util.stream.Collectors;


public class Main {

    private static Web3j web3j;
    private static ClientTransactionManager transactionManager = null;
    private static DefaultGasProvider gasProvider;
    private static CollectionConsentManager collectionConsentManager;
    private static ActorsManager actors;

    public static void main(String args[])  throws Exception {

        //create a Web3j instance to our local Ethereum node (Ganache)
        web3j = Web3j.build( new HttpService("HTTP://192.168.0.27:8545") );
        gasProvider = new DefaultGasProvider();
        collectionConsentManager = CollectionConsentManager.getConsentManager(web3j, gasProvider);

        //Getting the accounts generated by Ganache and Setting up controller and data subject actors
        actors = new ActorsManager( web3j.ethAccounts().send().getAccounts().toArray(new String[0]), web3j );
        menu();
        web3j.shutdown();
    }

    public static void menu(){
        DataBaseUser db= new DataBaseUser();

        db.setKeys();

        Scanner sn = new Scanner(System.in);
        boolean end = false; int option;
        while (!end) {
            System.out.println("1. Deploy a new SC");
            System.out.println("2. Exit");
            try {
                option = sn.nextInt();
                switch (option) {
                    case 1:
                        transactionManager = actors.transactionManagerDataSubject;

                        collectionConsentManager.newConsentContract(actors,db);

                        break;
                    case 2:
                        end = true;
                        break;
                    default:
                        System.out.println("Not a valid option");
                }
            } catch (InputMismatchException e) {
                System.out.println("Insert a valid option");
                sn.next();
            } catch (Exception e) {
                e.printStackTrace();
                sn.next();
            }
        }
    }


}
